parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: irismaster
    database_user: root
    database_password: Diablo2
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 90808cbf5a7d56ccc61cf8f387520295702ee561
    database_path: null
