seer_uk_iris_mail_mailbox:
    resource: "@SeerUKIrisMailMailboxBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
