parameters:
#    seer_uk_iris_mail_mailbox.example.class: SeerUK\IrisMail\MailboxBundle\Example

services:
#    seer_uk_iris_mail_mailbox.example:
#        class: %seer_uk_iris_mail_mailbox.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
